name: apartmaint
description: A cross-platform property management application for apartment maintenance with role-based access control.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  
  # Navigation
  go_router: ^14.8.1
  
  # UI
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_slidable: ^4.0.0
  intl: 0.19.0
  
  # Environment configuration
  flutter_dotenv: ^5.1.0
  
  # Payments
  flutter_stripe: ^11.4.0
  
  # Charting
  fl_chart: ^0.68.0

  # Logging
  logger: ^2.0.0

  # Utils
  url_launcher: ^6.1.12
  share_plus: ^10.1.4
  email_validator: ^2.1.17
  path_provider: ^2.1.0
  permission_handler: ^11.4.0
  connectivity_plus: ^6.1.3
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  
  cupertino_icons: ^1.0.5
  rxdart: ^0.28.0
  dash_chat_2: ^0.0.20
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Code generation
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  
  # Testing
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
